# Generated by Django 2.0.4 on 2019-06-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190612_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('order_code', models.CharField(max_length=250, unique=True)),
                ('total_number', models.IntegerField(verbose_name='总数量')),
                ('total_manoy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总金额')),
                ('pay_type', models.IntegerField(choices=[(1, '货到付款'), (2, '支付宝')], verbose_name='支付方式')),
                ('status', models.IntegerField(choices=[(1, '去付款'), (2, '已付款')], verbose_name='支付状态')),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'tb_sku_orders',
            },
        ),
        migrations.CreateModel(
            name='Ordersdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('order_code', models.CharField(max_length=250)),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goodsSku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GoodsSku', verbose_name='商品sku')),
            ],
            options={
                'verbose_name_plural': '订单详情表',
                'db_table': 'tb_sku_ordersdetail',
            },
        ),
    ]
