# Generated by Django 2.0.4 on 2019-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_orders_ordersdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_type',
            field=models.IntegerField(choices=[(2, '支付宝'), (1, '货到付款')], verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(2, '已付款'), (1, '去付款')], verbose_name='支付状态'),
        ),
    ]
