# Generated by Django 2.0.4 on 2019-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190620_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trade_no',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='支付编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(max_length=250, unique=True, verbose_name='订单编号'),
        ),
    ]
