# Generated by Django 2.0.4 on 2019-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190621_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, '去付款'), (2, '已付款')], verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trade_no',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
