# Generated by Django 2.0.4 on 2019-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190621_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '货到付款'), (2, '支付宝')], verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trade_no',
            field=models.CharField(default='', max_length=250),
        ),
    ]
